#!/usr/bin/groovy
pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }
    environment {
        PYTHONPATH = "${WORKSPACE}/section_4/code/cd_pipeline"
        DOCKER_HOST = "tcp://localhost:2375"
    }
    stages {
        stage("Build") {
            steps {
                dir('section_4/code/cd_pipeline') {
                    bat "docker build -t hands-on-jenkins/myapp:${BUILD_NUMBER} ."
                }
            }
        }
        stage("Deploy - Dev") {
            steps {
                script {
                    def containerName = "app_dev"
                    def port = "8888"
                    
            
                    powershell """
                        if (docker ps -a -q -f name=${containerName}) {
                            docker stop ${containerName}
                            docker rm ${containerName}
                        }
                        docker run -d -p ${port}:5000 --name ${containerName} hands-on-jenkins/myapp:${BUILD_NUMBER}
                    """
                }
            }
        }
        stage("Approve") {
            steps {
                timeout(time:1, unit:'DAYS') {
                    input('¿Desplegar a Live?')
                }
            }
        }
    }
}
